version: '3.4'

networks:
  mynekonetwork-dev:
    driver: bridge

services:
  nekospace.api:
    image: ${DOCKER_REGISTRY-}nekospaceapi
    depends_on:
        - "postgres_db"
    container_name: nekospace.api
    ports:
        - "8001:80"
    build:
      context: .
      dockerfile: NekoSpaceList/Dockerfile
    networks:
        - mynekonetwork-dev

  postgres_db:
    image: postgres:latest
    ports:
      - "5434:5432"
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresql
    environment:
        POSTGRES_DB: "anilist_db"
        POSTGRES_USER: "neko"
        POSTGRES_PASSWORD: "mya"
    networks:
        - mynekonetwork-dev


volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog:
    driver: local