version: '3.4'

services:
  nekospace.api:
    image: ${DOCKER_REGISTRY-}nekospaceapi
    depends_on:
        - "postgres_db"
    container_name: nekospace.api
    ports:
        - "2082:80"
        - "2083:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
     # - ASPNETCORE_Kestrel__Certificates__Default__Password=mypass123
     # - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    # volumes:
    #  - ~/.aspnet/https:/https:ro
    build:
      context: .
      dockerfile: NekoSpace.Core/Dockerfile


  postgres_db:
    image: postgres:latest
    ports:
      - "5434:5432"
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresql
    environment:
        POSTGRES_DB: "anilist_db"
        POSTGRES_USER: "neko"
        POSTGRES_PASSWORD: "mya"


volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog:
    driver: local
