version: '3.4'

services:
  nekospace.api:
    image: nekospaceapi:dev
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "NekoSpace.Core"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_nekospace.api$
    volumes:
      - C:\Users\Niko\source\repos\NekoSpace\NekoSpaceList\NekoSpace.Core:/app
      - C:\Users\Niko\source\repos\NekoSpace\NekoSpaceList:/src
      - C:\Users\Niko\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_nekospace.api$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_nekospace.api$ \"/app/bin/Debug/net7.0/NekoSpace.Core.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true